// Maps transaction descriptions to reward categories
// 200+ common merchants mapped

const merchantMap: Record<string, string> = {
  // ============ DINING / RESTAURANTS ============
  'MCDONALDS': 'dining',
  'MCDONALD': 'dining',
  'BURGER KING': 'dining',
  'WENDYS': 'dining',
  'WENDY\'S': 'dining',
  'TACO BELL': 'dining',
  'CHICK-FIL-A': 'dining',
  'CHICKFILA': 'dining',
  'CHIPOTLE': 'dining',
  'SUBWAY': 'dining',
  'DOMINOS': 'dining',
  'DOMINO\'S': 'dining',
  'PIZZA HUT': 'dining',
  'PAPA JOHN': 'dining',
  'STARBUCKS': 'dining',
  'DUNKIN': 'dining',
  'PANERA': 'dining',
  'OLIVE GARDEN': 'dining',
  'APPLEBEES': 'dining',
  'APPLEBEE': 'dining',
  'CHILIS': 'dining',
  'CHILI\'S': 'dining',
  'OUTBACK': 'dining',
  'RED LOBSTER': 'dining',
  'IHOP': 'dining',
  'DENNY\'S': 'dining',
  'DENNYS': 'dining',
  'WAFFLE HOUSE': 'dining',
  'PANDA EXPRESS': 'dining',
  'FIVE GUYS': 'dining',
  'IN-N-OUT': 'dining',
  'SHAKE SHACK': 'dining',
  'WINGSTOP': 'dining',
  'BUFFALO WILD': 'dining',
  'POPEYES': 'dining',
  'KFC': 'dining',
  'JACK IN THE BOX': 'dining',
  'SONIC DRIVE': 'dining',
  'ARBY\'S': 'dining',
  'ARBYS': 'dining',
  'JERSEY MIKE': 'dining',
  'JIMMY JOHN': 'dining',
  'NOODLES AND': 'dining',
  'CRACKER BARREL': 'dining',
  'TEXAS ROADHOUSE': 'dining',
  'LONGHORN STEAK': 'dining',
  'RUTH\'S CHRIS': 'dining',
  'CHEESECAKE FACTORY': 'dining',
  'PF CHANG': 'dining',
  'BENIHANA': 'dining',
  'SUSHI': 'dining',
  'THAI': 'dining',
  'GRUBHUB': 'dining',
  'UBER EATS': 'dining',
  'UBEREATS': 'dining',
  'DOORDASH': 'dining',
  'POSTMATES': 'dining',
  'SEAMLESS': 'dining',
  'CAVIAR': 'dining',
  'INSTACART': 'groceries',
  'SWEETGREEN': 'dining',
  'CAVA': 'dining',
  'TORCHY': 'dining',
  'MOD PIZZA': 'dining',
  'BLAZE PIZZA': 'dining',
  'TROPICAL SMOOTHIE': 'dining',
  'JAMBA': 'dining',
  'SMOOTHIE KING': 'dining',
  'RAISIN CANES': 'dining',
  'RAISING CANE': 'dining',
  'WHATABURGER': 'dining',
  'CULVER': 'dining',
  'FIREHOUSE SUB': 'dining',
  'ZAXBY': 'dining',

  // ============ GROCERIES ============
  'WHOLE FOODS': 'groceries',
  'WHOLEFOODS': 'groceries',
  'TRADER JOE': 'groceries',
  'KROGER': 'groceries',
  'SAFEWAY': 'groceries',
  'ALBERTSONS': 'groceries',
  'PUBLIX': 'groceries',
  'HEB': 'groceries',
  'H-E-B': 'groceries',
  'WEGMANS': 'groceries',
  'ALDI': 'groceries',
  'LIDL': 'groceries',
  'FOOD LION': 'groceries',
  'GIANT FOOD': 'groceries',
  'GIANT EAGLE': 'groceries',
  'STOP & SHOP': 'groceries',
  'STOP AND SHOP': 'groceries',
  'SHAW\'S': 'groceries',
  'SHAWS': 'groceries',
  'MEIJER': 'groceries',
  'PIGGLY WIGGLY': 'groceries',
  'HARRIS TEETER': 'groceries',
  'SPROUTS': 'groceries',
  'FRESH MARKET': 'groceries',
  'WM SUPERCENTER': 'groceries',
  'GROCERY': 'groceries',
  'MARKET BASKET': 'groceries',
  'WINN-DIXIE': 'groceries',
  'WINN DIXIE': 'groceries',
  'SAVE-A-LOT': 'groceries',
  'FOOD 4 LESS': 'groceries',
  'FOOD4LESS': 'groceries',
  'VONS': 'groceries',
  'RALPHS': 'groceries',
  'SMART & FINAL': 'groceries',
  'VALLARTA': 'groceries',
  'FOODMAXX': 'groceries',

  // ============ GAS ============
  'SHELL': 'gas',
  'CHEVRON': 'gas',
  'EXXON': 'gas',
  'MOBIL': 'gas',
  'BP ': 'gas',
  'SUNOCO': 'gas',
  'MARATHON': 'gas',
  'CITGO': 'gas',
  'VALERO': 'gas',
  'PHILLIPS 66': 'gas',
  'CONOCO': 'gas',
  'SPEEDWAY': 'gas',
  'WAWA': 'gas',
  'QUIKTRIP': 'gas',
  'QT ': 'gas',
  'CASEY': 'gas',
  'SHEETZ': 'gas',
  'RACETRAC': 'gas',
  'KWIK TRIP': 'gas',
  'PILOT': 'gas',
  'FLYING J': 'gas',
  'LOVES TRAVEL': 'gas',
  'LOVE\'S': 'gas',
  'CIRCLE K': 'gas',
  'MURPHY': 'gas',
  'COSTCO GAS': 'gas',
  'SAM\'S FUEL': 'gas',
  'SAMS FUEL': 'gas',
  'BUCCEE': 'gas',
  'BUC-EE': 'gas',
  'TEXACO': 'gas',
  'ARCO': 'gas',
  'SINCLAIR': 'gas',
  'GULF': 'gas',

  // ============ TRAVEL ============
  'UNITED AIRLINES': 'flights',
  'AMERICAN AIRLINES': 'flights',
  'DELTA AIR': 'flights',
  'SOUTHWEST AIR': 'flights',
  'JETBLUE': 'flights',
  'ALASKA AIR': 'flights',
  'SPIRIT AIR': 'flights',
  'FRONTIER AIR': 'flights',
  'HAWAIIAN AIR': 'flights',
  'ALLEGIANT': 'flights',
  'EXPEDIA': 'travel',
  'BOOKING.COM': 'hotels',
  'HOTELS.COM': 'hotels',
  'AIRBNB': 'hotels',
  'VRBO': 'hotels',
  'MARRIOTT': 'hotels',
  'HILTON': 'hotels',
  'HYATT': 'hotels',
  'IHG': 'hotels',
  'WYNDHAM': 'hotels',
  'BEST WESTERN': 'hotels',
  'HOLIDAY INN': 'hotels',
  'HAMPTON INN': 'hotels',
  'COURTYARD': 'hotels',
  'SHERATON': 'hotels',
  'WESTIN': 'hotels',
  'RADISSON': 'hotels',
  'TRAVELOCITY': 'travel',
  'KAYAK': 'travel',
  'PRICELINE': 'travel',
  'HOTWIRE': 'travel',
  'ORBITZ': 'travel',
  'TRIPADVISOR': 'travel',

  // ============ TRANSIT ============
  'UBER ': 'transit',
  'LYFT': 'transit',
  'METRO': 'transit',
  'MTA': 'transit',
  'BART': 'transit',
  'CALTRAIN': 'transit',
  'AMTRAK': 'transit',
  'GREYHOUND': 'transit',
  'BIRD SCOOTER': 'transit',
  'LIME SCOOTER': 'transit',
  'TOLL': 'transit',
  'PARKING': 'transit',
  'E-ZPASS': 'transit',
  'FASTRAK': 'transit',

  // ============ STREAMING ============
  'NETFLIX': 'streaming',
  'HULU': 'streaming',
  'DISNEY+': 'streaming',
  'DISNEY PLUS': 'streaming',
  'HBO MAX': 'streaming',
  'HBOMAX': 'streaming',
  'MAX.COM': 'streaming',
  'PARAMOUNT+': 'streaming',
  'PARAMOUNT PLUS': 'streaming',
  'PEACOCK': 'streaming',
  'APPLE TV': 'streaming',
  'APPLETV': 'streaming',
  'YOUTUBE PREM': 'streaming',
  'YOUTUBE TV': 'streaming',
  'SPOTIFY': 'streaming',
  'APPLE MUSIC': 'streaming',
  'TIDAL': 'streaming',
  'PANDORA': 'streaming',
  'AUDIBLE': 'streaming',
  'AMAZON PRIME': 'streaming',
  'SIRIUSXM': 'streaming',
  'SIRIUS': 'streaming',
  'CRUNCHYROLL': 'streaming',
  'FUBO': 'streaming',
  'SLING TV': 'streaming',
  'PHILO': 'streaming',
  'DISCOVERY+': 'streaming',
  'ESPN+': 'streaming',
  'DAZN': 'streaming',
  'AMAZON VIDEO': 'streaming',

  // ============ ONLINE SHOPPING ============
  'AMAZON': 'amazon',
  'AMAZON.COM': 'amazon',
  'AMZN': 'amazon',
  'WALMART.COM': 'online_shopping',
  'WAL-MART.COM': 'online_shopping',
  'TARGET.COM': 'online_shopping',
  'EBAY': 'online_shopping',
  'ETSY': 'online_shopping',
  'WAYFAIR': 'online_shopping',
  'OVERSTOCK': 'online_shopping',
  'ZAPPOS': 'online_shopping',
  'ALIEXPRESS': 'online_shopping',
  'WISH.COM': 'online_shopping',
  'SHEIN': 'online_shopping',
  'TEMU': 'online_shopping',

  // ============ RETAIL / IN-STORE ============
  'WALMART': 'groceries',
  'WAL-MART': 'groceries',
  'TARGET': 'target',
  'COSTCO': 'costco',
  'SAM\'S CLUB': 'groceries',
  'SAMS CLUB': 'groceries',
  'BJ\'S': 'groceries',
  'BJS WHOLESALE': 'groceries',
  'DOLLAR GENERAL': 'retail',
  'DOLLAR TREE': 'retail',
  'FAMILY DOLLAR': 'retail',
  'FIVE BELOW': 'retail',
  'ROSS': 'retail',
  'TJ MAXX': 'retail',
  'TJMAXX': 'retail',
  'MARSHALLS': 'retail',
  'NORDSTROM': 'retail',
  'MACYS': 'retail',
  'MACY\'S': 'retail',
  'BLOOMINGDALE': 'retail',
  'SAKS': 'retail',
  'NEIMAN MARCUS': 'retail',
  'JC PENNEY': 'retail',
  'JCPENNEY': 'retail',
  'KOHLS': 'retail',
  'KOHL\'S': 'retail',
  'OLD NAVY': 'retail',
  'GAP': 'retail',
  'BANANA REPUBLIC': 'retail',
  'H&M': 'retail',
  'ZARA': 'retail',
  'UNIQLO': 'retail',
  'NIKE': 'retail',
  'ADIDAS': 'retail',

  // ============ HOME IMPROVEMENT ============
  'HOME DEPOT': 'home_improvement',
  'LOWES': 'home_improvement',
  'LOWE\'S': 'home_improvement',
  'MENARDS': 'home_improvement',
  'ACE HARDWARE': 'home_improvement',
  'TRUE VALUE': 'home_improvement',
  'IKEA': 'home_improvement',
  'BED BATH': 'home_improvement',
  'POTTERY BARN': 'home_improvement',
  'RESTORATION HARDWARE': 'home_improvement',
  'WILLIAMS SONOMA': 'home_improvement',
  'CRATE AND BARREL': 'home_improvement',
  'WEST ELM': 'home_improvement',

  // ============ DRUGSTORES / PHARMACY ============
  'CVS': 'drugstores',
  'WALGREENS': 'drugstores',
  'RITE AID': 'drugstores',
  'RITE-AID': 'drugstores',
  'DUANE READE': 'drugstores',

  // ============ ENTERTAINMENT ============
  'AMC THEATRE': 'entertainment',
  'AMC THEATER': 'entertainment',
  'REGAL CINEMA': 'entertainment',
  'CINEMARK': 'entertainment',
  'FANDANGO': 'entertainment',
  'TICKETMASTER': 'entertainment',
  'STUBHUB': 'entertainment',
  'SEATGEEK': 'entertainment',
  'VIVID SEATS': 'entertainment',
  'BOWLING': 'entertainment',
  'DAVE AND BUSTER': 'entertainment',
  'TOPGOLF': 'entertainment',
  'SIX FLAGS': 'entertainment',
  'DISNEY PARK': 'entertainment',
  'UNIVERSAL STUD': 'entertainment',
  'SEAWORLD': 'entertainment',
  'LEGOLAND': 'entertainment',

  // ============ GYM / FITNESS ============
  'PLANET FITNESS': 'fitness',
  'LA FITNESS': 'fitness',
  'EQUINOX': 'fitness',
  'ORANGETHEORY': 'fitness',
  'CROSSFIT': 'fitness',
  'PELOTON': 'fitness',
  'LIFETIME FITNESS': 'fitness',
  '24 HOUR FITNESS': 'fitness',
  'ANYTIME FITNESS': 'fitness',
  'GOLD\'S GYM': 'fitness',
  'GOLDS GYM': 'fitness',
  'YMCA': 'fitness',
  'CRUNCH FITNESS': 'fitness',

  // ============ PHONE / INTERNET / UTILITIES ============
  'VERIZON': 'phone',
  'AT&T': 'phone',
  'T-MOBILE': 'phone',
  'TMOBILE': 'phone',
  'SPRINT': 'phone',
  'MINT MOBILE': 'phone',
  'CRICKET': 'phone',
  'COMCAST': 'internet',
  'XFINITY': 'internet',
  'SPECTRUM': 'internet',
  'COX COMM': 'internet',
  'FRONTIER COMM': 'internet',
  'CENTURYLINK': 'internet',
  'GOOGLE FIBER': 'internet',
  'STARLINK': 'internet',

  // ============ UTILITIES ============
  'ELECTRIC': 'utilities',
  'POWER COMPANY': 'utilities',
  'GAS COMPANY': 'utilities',
  'WATER UTILITY': 'utilities',
  'WATER DEPT': 'utilities',
  'SEWER': 'utilities',
  'WASTE MANAGE': 'utilities',
  'PG&E': 'utilities',
  'DUKE ENERGY': 'utilities',
  'SOUTHERN COMPANY': 'utilities',
  'DOMINION ENERGY': 'utilities',
  'CON EDISON': 'utilities',
  'CONED': 'utilities',
  'NATIONAL GRID': 'utilities',

  // ============ INSURANCE ============
  'GEICO': 'insurance',
  'STATE FARM': 'insurance',
  'PROGRESSIVE': 'insurance',
  'ALLSTATE': 'insurance',
  'USAA': 'insurance',
  'LIBERTY MUTUAL': 'insurance',
  'FARMERS INS': 'insurance',

  // ============ HEALTH ============
  'HOSPITAL': 'health',
  'MEDICAL': 'health',
  'DENTAL': 'health',
  'PHARMACY': 'drugstores',
  'URGENT CARE': 'health',
  'LABCORP': 'health',
  'QUEST DIAG': 'health',

  // ============ EDUCATION ============
  'UNIVERSITY': 'education',
  'COLLEGE': 'education',
  'TUITION': 'education',
  'STUDENT': 'education',
  'COURSERA': 'education',
  'UDEMY': 'education',

  // ============ PET ============
  'PETCO': 'retail',
  'PETSMART': 'retail',
  'CHEWY': 'online_shopping',
  'VET': 'health',
  'VETERINARY': 'health',

  // ============ AUTO ============
  'JIFFY LUBE': 'auto',
  'AUTOZONE': 'auto',
  'O\'REILLY AUTO': 'auto',
  'ADVANCE AUTO': 'auto',
  'NAPA AUTO': 'auto',
  'CARMAX': 'auto',
  'ENTERPRISE RENT': 'auto',
  'HERTZ': 'auto',
  'AVIS': 'auto',
  'BUDGET RENT': 'auto',
  'NATIONAL CAR': 'auto',

  // ============ APPLE / TECH ============
  'APPLE.COM': 'apple',
  'APPLE STORE': 'apple',
  'ITUNES': 'apple',
  'APP STORE': 'apple',
  'ICLOUD': 'apple',
  'GOOGLE *': 'online_shopping',
  'MICROSOFT': 'online_shopping',
  'BEST BUY': 'retail',
  'MICRO CENTER': 'retail',
};

export function categorizeTransaction(description: string): string {
  const upper = description.toUpperCase().trim();

  // Check exact and partial matches
  for (const [keyword, category] of Object.entries(merchantMap)) {
    if (upper.includes(keyword)) {
      return category;
    }
  }

  // Heuristic fallbacks
  if (upper.includes('RESTAURANT') || upper.includes('CAFE') || upper.includes('GRILL') ||
      upper.includes('BISTRO') || upper.includes('BAKERY') || upper.includes('DINER') ||
      upper.includes('PIZZ') || upper.includes('BBQ') || upper.includes('BREW') ||
      upper.includes('BAR ') || upper.includes('PUB ') || upper.includes('TAQUERIA') ||
      upper.includes('EATERY') || upper.includes('KITCHEN') || upper.includes('FOOD TRUCK')) {
    return 'dining';
  }

  if (upper.includes('AIRLINE') || upper.includes('AIR LINE') || upper.includes('AIRWAYS')) {
    return 'flights';
  }

  if (upper.includes('HOTEL') || upper.includes('RESORT') || upper.includes('INN ') ||
      upper.includes('LODGE') || upper.includes('MOTEL')) {
    return 'hotels';
  }

  if (upper.includes('FUEL') || upper.includes('PETROL') || upper.includes('GASOLINE')) {
    return 'gas';
  }

  if (upper.includes('GROCERY') || upper.includes('SUPERMARKET') || upper.includes('FOOD STORE') ||
      upper.includes('PRODUCE')) {
    return 'groceries';
  }

  if (upper.includes('PHARMACY') || upper.includes('DRUG')) {
    return 'drugstores';
  }

  return 'uncategorized';
}

export const CATEGORY_LABELS: Record<string, string> = {
  dining: 'Dining & Restaurants',
  groceries: 'Groceries',
  gas: 'Gas & Fuel',
  travel: 'Travel',
  flights: 'Flights',
  hotels: 'Hotels',
  transit: 'Transit & Rideshare',
  streaming: 'Streaming Services',
  entertainment: 'Entertainment',
  online_shopping: 'Online Shopping',
  amazon: 'Amazon',
  retail: 'Retail',
  drugstores: 'Drugstores & Pharmacy',
  home_improvement: 'Home Improvement',
  fitness: 'Gym & Fitness',
  phone: 'Phone & Wireless',
  internet: 'Internet & Cable',
  utilities: 'Utilities',
  insurance: 'Insurance',
  health: 'Health & Medical',
  education: 'Education',
  auto: 'Auto & Car',
  apple: 'Apple',
  apple_pay: 'Apple Pay',
  costco: 'Costco',
  target: 'Target',
  whole_foods: 'Whole Foods',
  uncategorized: 'Other / Uncategorized',
};

export function getCategoryLabel(category: string): string {
  return CATEGORY_LABELS[category] || category.charAt(0).toUpperCase() + category.slice(1).replace(/_/g, ' ');
}
